create table chat_sessions (
   id            raw(16) default sys_guid() primary key,
   user_id       varchar2(64) not null,
   title         varchar2(255),
   model         varchar2(64) not null,
   system_prompt clob,
   metadata      clob,
   created_at    timestamp with time zone default systimestamp not null,
   updated_at    timestamp with time zone default systimestamp not null
);

create table chat_messages (
   id         number generated by default as identity primary key,
   session_id raw(16) not null,
   role       varchar2(20) not null,
   content    clob not null,
   metadata   clob,
   created_at timestamp with time zone default systimestamp not null,
   constraint fk_chat_messages_session foreign key ( session_id )
      references chat_sessions ( id )
);

create index idx_chat_messages_session on
   chat_messages (
      session_id,
      created_at
   );

create index idx_chat_sessions_user on
   chat_sessions (
      user_id,
      updated_at
   );